modLoader="javafml"
loaderVersion="[25,)"
[[mods]]
modId="customskinloader"
version="${modFullVersion}"
displayName="CustomSkinLoader"
description='''
Custom Skin Loader for Minecraft
'''
issueTrackerURL="https://github.com/xfl03/MCCustomSkinLoader/issues"
displayURL="https://github.com/xfl03/MCCustomSkinLoader"
authors=["xfl03", "JLChnToZ"]
[[dependencies.customskinloader]]
modId="forge"
mandatory=true
versionRange="[25,)"
ordering="NONE"
side="CLIENT"